### PR TITLE
Support for NanoHeart board

### PR DESCRIPTION
**Pull request by RaD**
I have cleaned the sources changing TAB symbols by two spaces, so now it look fine in every editor.
I have added a support for my [NanoHeart board](http://blog.securelayer.ru/doku.php/reprap/electronics/nanoheart).

nanoheart

### CODE REVIEW

**Comment by RaD** [comment]
So, should I need to revoke this pull request and remove "replace commit" out?

About AIO->DIO. Do you mean I should replace AIO0->DIO14, AIO1->DIO15 and so on?
But keep AIOn for heater sensors, right?

Nano v3 has a LED on DIO13 pin.

**Comment by Traumflug** [comment]
> So, should I need to revoke this pull request and remove "replace commit" out?

Just do nothing. I'll add a commit for this file an close the pull request without merging.

> Nano v3 has a LED on DIO13 pin.

Ah, I forgot about the Nano its self. :-)

Will do that commit before too long, just not right now.

**Comment by RaD** [comment]
Just add a file board.nanoheart...

**Comment by RaD** [comment]
Also, I think that using AIOx in configuration will be good because of these values are printed on Nano's PCB.

**Comment by Traumflug** [comment]
> these values are printed on Nano's PCB.

OK, that's actually a reason. :-)

Just picked the commit onto experimental, just added a few more MCU options for those with similar Arduinos (Diecimilia, Uno, etc.). Default is still the ATmega328P. See a13e00893dbef454fcad5566033285b7d7843504

I see you took care of the details, like getting pins for max endstops right, even with them disabled. Excellent! Thanks again for the contribution.

**Pull request closed without merging**
